blank_issues_enabled: true
contact_links:
  - name: ğŸ¥ Visual Effects Video Playlist 
    url: https://www.youtube.com/playlist?list...
    about: View the Visual Effects examples playlist on YouTube
  - name: ğŸ‘©â€ğŸ’» World of Zero
    url: https://worldofzero.com
    about: The World of Zero website
